# Generated by Django 4.2.20 on 2026-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
