version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django-backend-prod
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file: .env.prod
    depends_on:
      - postgres
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONUNBUFFERED=1
  postgres:
    image: postgres:15
    container_name: postgres-db-prod
    restart: always
    ports:
      - "5432:5432"
    env_file: .env.prod
    volumes:
      - postgres-db-prod:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  nginx:
    image: nginx
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/keys:/etc/letsencrypt/keys:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - backend

volumes:
  postgres-db-prod: