version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fishtail-backend-dev
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - backend_media:/app/media
      - backend_static:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    restart: unless-stopped
    networks:
      - fishtail-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: fishtail-postgres-dev
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - fishtail-network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  redis:
    image: redis:7-alpine
    container_name: fishtail-redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - fishtail-network

volumes:
  postgres_data:
    driver: local
  backend_media:
    driver: local
  backend_static:
    driver: local

networks:
  fishtail-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
