# Generated by Django 4.2.20 on 2026-08-22 15:07

import customer.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +819012345678 or 09012345678).', regex='^\\+?\\d{9,15}$')], verbose_name='Phone Number')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('home_address', models.TextField()),
                ('parent_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +819012345678 or 09012345678).', regex='^\\+?\\d{9,15}$')], verbose_name='Parent Phone Number')),
                ('visa_type', models.CharField(choices=[('Student', 'Student'), ('Skilled Labor', 'Skilled Labor'), ('Specified Skilled Worker', 'Specified Skilled Worker'), ('Technical Intern Training', 'Technical Intern Training'), ('Engineer/Specialist in Humanities/International Services', 'Engineer/Humanities/International'), ('Working Holiday', 'Working Holiday'), ('Spouse or Child of Japanese National', 'Spouse/Child of Japanese'), ('Permanent Resident', 'Permanent Resident'), ('Dependent', 'Dependent'), ('Other', 'Other')], max_length=100)),
                ('workplace_or_school_name', models.CharField(max_length=255)),
                ('workplace_or_school_address', models.TextField()),
                ('workplace_or_school_phone', models.CharField(max_length=20)),
                ('zairyu_card_number', models.CharField(max_length=50)),
                ('zairyu_card_expire_date', models.DateField()),
                ('zairyu_card_pdf', models.FileField(blank=True, null=True, upload_to='documents/zairyu_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), customer.models.validate_file_size])),
                ('passport_pdf', models.FileField(blank=True, null=True, upload_to='documents/passports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), customer.models.validate_file_size])),
                ('student_card_pdf', models.FileField(blank=True, null=True, upload_to='documents/student_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), customer.models.validate_file_size])),
                ('status', models.BooleanField(default=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('status', 'name', 'date_of_birth'), name='unique_customer_name_dob_status'),
        ),
    ]
