# Generated by Django 4.2.20 on 2026-08-22 15:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Monthly target amount in Japanese Yen', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('target_month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Target month (1-12)')),
                ('target_year', models.PositiveIntegerField(help_text='Target year')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional notes about the target', null=True)),
                ('assigned_by', models.ForeignKey(help_text='Super user who assigned this target', on_delete=django.db.models.deletion.CASCADE, related_name='targets_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('target_to', models.ForeignKey(help_text='User who is assigned this target', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_targets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Target',
                'verbose_name_plural': 'Monthly Targets',
                'ordering': ['-target_year', '-target_month', 'target_to__first_name'],
                'unique_together': {('target_to', 'target_month', 'target_year')},
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(help_text='Name of the customer/tenant', max_length=255)),
                ('customer_number', models.CharField(help_text='Customer contact number (maximum 11 digits)', max_length=11)),
                ('building_address', models.TextField(help_text='Full address of the building/property')),
                ('contract_date', models.DateField(help_text='Date when the contract was signed')),
                ('agent_fee', models.DecimalField(decimal_places=2, help_text='Agent fee amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ad_fee', models.DecimalField(decimal_places=2, help_text='Advertisement fee amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ad_fee_received_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual AD fee amount received after deductions', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ad_fee_transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transfer fee deducted from the AD fee', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ad_fee_received_date', models.DateField(blank=True, help_text='Date the AD fee was received', null=True)),
                ('ad_fee_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ad_fee_memo', models.TextField(blank=True, help_text='AD fee receipt reference or notes')),
                ('support_phone', models.CharField(help_text='24/7 support phone number (maximum 11 digits)', max_length=11)),
                ('contract_type', models.CharField(choices=[('fix_term', 'Fix Term'), ('regular', 'Regular')], help_text='Type of rental contract', max_length=20)),
                ('cancellation_notice_period', models.CharField(help_text='Notice period required for cancellation', max_length=255)),
                ('cancellation_period', models.CharField(help_text='Cancellation period details', max_length=255)),
                ('cancellation_charge', models.CharField(help_text='Charges applicable on cancellation', max_length=255)),
                ('deposit_fee', models.CharField(help_text='Deposit fee amount and terms', max_length=255)),
                ('cleaning_charge', models.BooleanField(default=False, help_text='Whether cleaning charge is applicable')),
                ('emergency_contact_person', models.CharField(help_text='Emergency contact person name', max_length=255)),
                ('emergency_phone', models.CharField(help_text='Emergency contact phone number (maximum 11 digits)', max_length=11)),
                ('renew_fee', models.CharField(help_text='Renewal fee amount and terms', max_length=255)),
                ('living_num_people', models.PositiveIntegerField(help_text='Number of people living in the property')),
                ('rent_payment_date', models.CharField(help_text='Rent payment due date', max_length=255)),
                ('memo', models.TextField(blank=True, help_text='Additional notes or memo about the contract', null=True)),
                ('management_company_name', models.CharField(help_text='Name of the management company or person', max_length=255)),
                ('management_company_phone_number', models.CharField(help_text='Management company phone number (maximum 11 digits)', max_length=11)),
                ('ad_fee_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ad_fees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('target_to', models.ForeignKey(blank=True, help_text='Target this rental contract belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to='targets.target')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Contract',
                'verbose_name_plural': 'Rental Contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
