from django.urls import path
from . import views

app_name = 'finance'

urlpatterns = [
    path('office-expenses/', views.office_expense_list, name='office_expenses'),
    path('office-expenses/add/', views.office_expense_create, name='office_expense_add'),
    path('office-expenses/lookup/', views.office_expense_lookup, name='office_expense_lookup'),
    path('office-expenses/<int:pk>/', views.office_expense_detail, name='office_expense_detail'),
    path('office-expenses/<int:pk>/edit/', views.office_expense_edit, name='office_expense_edit'),
    path('office-expenses/<int:pk>/decision/', views.office_expense_decide, name='office_expense_decide'),
    path('office-expenses/card-settlements/add/', views.card_settlement_create, name='card_settlement_add'),
    path('office-expenses/card-settlements/', views.card_settlement_list, name='card_settlements'),
    path('office-expenses/card-settlements/preview/', views.card_settlement_preview, name='card_settlement_preview'),
    path('office-expenses/card-settlements/<int:pk>/', views.card_settlement_detail, name='card_settlement_detail'),
    path('office-expenses/card-settlements/<int:pk>/edit/', views.card_settlement_edit, name='card_settlement_edit'),
    path('office-expenses/card-settlements/<int:pk>/decision/', views.card_settlement_decide, name='card_settlement_decide'),
    path('office-expenses/payment-accounts/', views.office_payment_accounts, name='office_payment_accounts'),
    path('office-expenses/payment-accounts/banks/add/', views.office_bank_account_create, name='office_bank_account_add'),
    path('office-expenses/payment-accounts/banks/<int:pk>/edit/', views.office_bank_account_edit, name='office_bank_account_edit'),
    path('office-expenses/payment-accounts/cards/add/', views.office_credit_card_create, name='office_credit_card_add'),
    path('office-expenses/payment-accounts/cards/<int:pk>/edit/', views.office_credit_card_edit, name='office_credit_card_edit'),
    path('revenues/', views.revenues, name='revenues'),
    path('revenues/real-estate/', views.real_estate_revenue, name='real_estate_revenue'),
    path('revenues/real-estate/<int:pk>/confirm-ad-fee/', views.confirm_ad_fee_receipt, name='confirm_ad_fee_receipt'),
    path('third-party-services/', views.third_party_services, name='third_party_services'),
    path('third-party-services/add/', views.third_party_service_create, name='third_party_service_create'),
    path('third-party-services/<int:pk>/', views.third_party_service_detail, name='third_party_service_detail'),
    path('third-party-services/<int:pk>/edit/', views.third_party_service_edit, name='third_party_service_edit'),
    path('revenues/<int:pk>/', views.revenue_detail, name='revenue_detail'),
    path('expenses/', views.expenses, name='expenses'),  # 👈 root view
    path('expenses/add/', views.hostel_expense_create, name='hostel_expense_add'),
    path('expenses/<int:pk>/edit/', views.hostel_expense_edit, name='hostel_expense_edit'),
    path('expenses/<int:pk>/', views.hostel_expense_detail, name='hostel_expense_detail'),
    path('utility-expenses/add/', views.utility_expense_create, name='utility_expense_add'),
    path('utility-expenses/<int:pk>/edit/', views.utility_expense_edit, name='utility_expense_edit'),
    path('utility-expenses/<int:pk>/', views.utility_expense_detail, name='utility_expense_detail'),
    path('registration/<int:customer_id>/', views.registration_fee, name='registration_fee'),
    path('rent/<int:customer_id>/', views.monthly_rent, name='monthly_rent'), 
    path('rent/<int:customer_id>/get-prepaid/', views.get_prepaid_amount_for_month, name='get_prepaid_amount'),
    path('rent/<int:customer_id>/validate-month/', views.validate_rent_month, name='validate_rent_month'),
    path('notification/', views.notification, name='notification'),
    path('staff-expenses/dashboard/', views.staff_expense_dashboard, name='staff_expense_dashboard'),
    path('staff-expenses/<int:pk>/status/', views.staff_expense_update_status, name='staff_expense_update_status'),
    path('staff-expenses/', views.staff_expense_list, name='staff_expense_list'),
    path('staff-expenses/add/', views.staff_expense_create, name='staff_expense_create'),
    path('staff-expenses/<int:pk>/edit/', views.staff_expense_edit, name='staff_expense_edit'),
]
