# Generated by Django 4.2.20 on 2026-08-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('INTERNET', 'Internet'), ('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('GAS', 'Gas')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid for the utility.', max_digits=10)),
                ('billing_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035)], default=finance.models.current_year, help_text='Year the utility bill was issued.')),
                ('billing_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Month the utility bill was issued.')),
                ('date_from', models.DateField(help_text='Start date of the usage period.', verbose_name='Usage Start Date')),
                ('date_to', models.DateField(help_text='End date of the usage period.', verbose_name='Usage End Date')),
                ('paid_date', models.DateField(help_text='Date when the expense was paid.', verbose_name='Paid Date')),
                ('usage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Usage measured (e.g., kWh, m³, GB).', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes.')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status of the expense.', max_length=10)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_utility_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_expenses', to='hostel.hostel')),
                ('paid_by', models.ForeignKey(blank=True, help_text='User who recorded or paid the expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utility Expense',
                'verbose_name_plural': 'Utility Expenses',
                'ordering': ['-billing_year', '-billing_month'],
            },
        ),
        migrations.CreateModel(
            name='StaffExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Current approval status of the staff expense.', max_length=20)),
                ('expense_type', models.CharField(choices=[('TRAVEL', 'Travel'), ('PURCHASE', 'Purchase'), ('OTHER', 'Other')], default='TRAVEL', help_text='Category of the staff expense.', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the expense period.')),
                ('end_date', models.DateField(help_text='End date of the expense period.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total staff expense amount.', max_digits=12)),
                ('memo', models.TextField(help_text='Additional information about the staff expense.')),
                ('status_memo', models.TextField(blank=True, help_text='Memo recorded when the approval status is changed.')),
                ('transaction_code', models.CharField(db_index=True, editable=False, help_text='Unique transaction code for this staff expense.', max_length=6, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved or rejected the expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee who submitted the staff expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_expenses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Expense',
                'verbose_name_plural': 'Staff Expenses',
            },
        ),
        migrations.CreateModel(
            name='HostelRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('registration_fee', 'Registration Fee'), ('rent', 'Rent')], max_length=20)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035)], default=finance.models.current_year)),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('deposit_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('initial_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('initial_fee_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('initial_fee_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('internet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rent_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('', 'Normal Payment'), ('prepaid', 'Prepaid Payment'), ('postpaid', 'Postpaid Payment')], default='', max_length=10)),
                ('prepaid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid in advance (for prepaid) or amount carried forward (for postpaid)', max_digits=10, null=True)),
                ('collected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount collected from customer', max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_date', models.DateField()),
                ('purchased_by', models.CharField(max_length=255)),
                ('memo', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('transaction_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='utilityexpense',
            constraint=models.UniqueConstraint(fields=('hostel', 'billing_year', 'billing_month', 'expense_type'), name='unique_utility_expense_per_hostel_year_month_type'),
        ),
        migrations.AddConstraint(
            model_name='hostelrevenue',
            constraint=models.UniqueConstraint(fields=('title', 'customer', 'year', 'month'), name='unique_revenue_transaction'),
        ),
    ]
