# Generated by Django 4.2.20 on 2026-08-12 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Current approval status of the travel expense.', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the travel.')),
                ('end_date', models.DateField(help_text='End date of the travel.')),
                ('memo', models.TextField(blank=True, help_text='Additional information about the travel expense.')),
                ('transaction_code', models.CharField(db_index=True, editable=False, help_text='Unique transaction code for this travel expense.', max_length=6, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved or rejected the expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_travel_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee who submitted the travel expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_expenses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
