# Generated by Django 4.2.20 on 2026-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_travelexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Total travel expense amount.', max_digits=12),
            preserve_default=False,
        ),
    ]
