# Generated by Django 4.2.20 on 2026-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_travelexpense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelexpense',
            name='memo',
            field=models.TextField(help_text='Additional information about the travel expense.'),
        ),
    ]
